### 크루원 리스트 조회
GET http://localhost:8080/api/v1/admin/crewMemberList

### 크루 조회
GET http://localhost:8080/api/v1/admin/crewList

### 크루 상세정보 조회(1번크루)
GET http://localhost:8080/api/v1/crew/detail/1

### 크루원 삭제
DELETE http://localhost:8080/api/v1/admin/list/user04/delete

### 크루 삭제
DELETE http://localhost:8080/api/v1/admin/list/6/crewdelete

### 신고대상유저 신고목록 조회
GET http://localhost:8080/api/v1/admin/reportlist/user

### 신고대상크루 신고목록 조회
GET http://localhost:8080/api/v1/admin/reportlist/crew

###
POST http://localhost:8080/admin/login
Content-Type: application/json
Accept: */*
Access-Control-Allow-Origin: *

{
  "adminId": "admin1",
  "adminPw": "admin"
}