### 크루의 인증게시판 리스트 조회
GET http://localhost:8080/api/v1/certificationpost/58/list


### 크루별 인증게시판 리스트 조회 페이징처리
GET http://localhost:8080/api/v1/certificationpost/2/post

### 포스트 상세조회
GET http://localhost:8080/api/v1/certificationpost/2/list/details


### 포스트 상세조회
GET http://localhost:8080/api/v1/certificationcomment/2/list/detail



### 인증게시판 글 생성
PUT http://localhost:8080/api/v1/certificationpost/2/regist
content-type: application/json

{
    "postTitle": "새로운 인증글22",
    "postContent": "11/23 인증"
}


### 인증 게시판에 댓글 등록
PUT http://localhost:8080/api/v1/certificationcomment/2/list/comment
content-type: application/json

{
    "commentContent": "새로운 인증 댓글"
}



