###크루신청현황 상세 조회(1번)
GET http://localhost:8080/api/v1/crewlist/select/detail/1

###신청대기 크루리스트 조회
GET http://localhost:8080/api/v1/crewlist/select/waitstatus/2

###크루원 받아주기(상태를 1로변경)
PUT http://localhost:8080/api/v1/crewlist/agreestatus
Content-Type: application/json

{
  "id": {
    "userId": "zusung2",
    "crewId": 1
  }
}

###크루원 거절하기(상태를 2로변경)
PUT http://localhost:8080/api/v1/crewlist/rejectionstatus
Content-Type: application/json

{
  "id": {
    "userId": "zusung2",
    "crewId": 1
  }
}

###유저 가입 크루 조회
GET http://localhost:8080/api/v1/crewlist/sean1007@naver.com/crew

###크루 가입 신청
POST http://localhost:8080/api/v1/crewlist/apply/20
Content-Type: application/json

{
  "user": {
    "userId": "zusung2"
  }
}