###크루신청현황 상세 조회(1번)
GET http://localhost:8080/api/v1/crewlist/select/detail/1

###신청대기 크루리스트 조회
GET http://localhost:8080/api/v1/crewlist/select/waitstatus/2

###크루원 받아주기(상태를 1로변경)
PUT http://localhost:8080/api/v1/crewlist/agreestatus
Content-Type: application/json

{
  "user": {
    "userId": "test1"
  },
  "crew": {
    "crewId": 1
  },
  "id": {
    "userId": "test1",
    "crewId": 1
  }
}

###크루원 거절하기(상태를 2로변경)
PUT http://localhost:8080/api/v1/crewlist/rejectionstatus
Content-Type: application/json

{
  "user": {
    "userId": "test4"
  },
  "crew": {
    "crewId": 1
  },
  "id": {
    "userId": "test4",
    "crewId": 1
  }
}

###유저 가입 크루 조회
GET http://localhost:8080/api/v1/crewlist/seyoung2/crew