### 전체 크루 리스트 조회 페이징 10개씩
GET http://localhost:8080/api/v1/crew/list

### 전체 크루 리스트 조회 페이징 5개씩
GET http://localhost:8080/api/v1/crew/list/five

### 카테고리 운동 크루 리스트 조회
GET http://localhost:8080/api/v1/crew/list/exercise

### 카테고리 공부 크루 리스트 조회
GET http://localhost:8080/api/v1/crew/list/study

### 카테고리 습관 크루 리스트 조회
GET http://localhost:8080/api/v1/crew/list/habit

### 카테고리 기타 크루 리스트 조회
GET http://localhost:8080/api/v1/crew/list/etc

### 모집상태 1 리스트 조회
GET http://localhost:8080/api/v1/crew/list/recruitmentstatusok

### 모집상태 0 리스트 조회
GET http://localhost:8080/api/v1/crew/list/recruitmentstatusno

### 크루 상세정보 조회(1번크루)
GET http://localhost:8080/api/v1/crew/detail/1

### 크루 소개글 조회(1번크루)
GET http://localhost:8080/api/v1/crew/detail/1/intro

### 크루 소개글 수정
PUT http://localhost:8080/api/v1/crew/intro
Content-Type: application/json

{
  "crewId": "1",
  "introduction": "수정테스트입니다34"
}

### 크루 만들기
POST http://localhost:8080/api/v1/crew/register
Content-Type: application/json

{
  "crewName": "테스트크루1901901234dfa1234",
  "captain": {
    "userId": "zusung1"
  },
  "introduction": "크루만들기테스트중입니다3",
  "crewCategoryCode": {
    "categoryCode": 4
  },
  "startDate": "2023-11-16",
  "endDate": "2024-11-20",
  "crewRecruitmentPost": "크루모집글제목테스트3",
  "crewRecruitmentContent": "크루모집글내용테스트3"
}

### 크루이름 검색 조회
GET http://localhost:8080/api/v1/crew/list/search?s=붕어빵

### 캡틴 이름을 통해 조회
GET http://localhost:8080/api/v1/crew/list/sean1007@naver.com/mypost

### 크루 삭제
DELETE http://localhost:8080/api/v1/crew/crewdelete/36

### 크루 업데이트
PUT http://localhost:8080/api/v1/crew/update
Content-Type: application/json

{
  "crewId": 1,
  "crewName": "수정테스트",
  "startDate": "2022-11-11",
  "endDate": "2023-12-10",
  "crewRecruitmentPost": "수정테스트중입니다",
  "crewRecruitmentContent": "수정테스트내용입니다",
  "recruitmentStatus": "0",
  "crewCategoryCode": {
    "categoryCode": 3
  }
}