### 전체 크루 리스트 조회
GET http://localhost:8080/api/v1/crew/list

### 카테고리 운동 크루 리스트 조회
GET http://localhost:8080/api/v1/crew/list/exercise

### 카테고리 공부 크루 리스트 조회
GET http://localhost:8080/api/v1/crew/list/study

### 카테고리 습관 크루 리스트 조회
GET http://localhost:8080/api/v1/crew/list/habit

### 카테고리 기타 크루 리스트 조회
GET http://localhost:8080/api/v1/crew/list/etc

### 모집상태 1 리스트 조회
GET http://localhost:8080/api/v1/crew/list/recruitmentstatusok

### 모집상태 0 리스트 조회
GET http://localhost:8080/api/v1/crew/list/recruitmentstatusno

### 크루 상세정보 조회(1번크루)
GET http://localhost:8080/api/v1/crew/detail/1

### 크루 소개글 조회(1번크루)
GET http://localhost:8080/api/v1/crew/detail/1/intro

### 크루 소개글 수정
PUT http://localhost:8080/api/v1/crew/intro
Content-Type: application/json

{
  "crewId": "1",
  "introduction": "수정테스트입니다33"
}

### 크루 만들기
POST http://localhost:8080/api/v1/crew/register
Content-Type: application/json

{
  "crewName": "테스트크루3",
  "captain": {
    "userId": "zusung1"
  },
  "introduction": "크루만들기테스트중입니다3",
  "crewCategoryCode": {
    "categoryCode": 4
  },
  "startDate": "2023-11-11",
  "endDate": "2024-11-11",
  "crewRecruitmentPost": "크루모집글제목테스트3",
  "crewRecruitmentContent": "크루모집글내용테스트3"
}