### 공지사항 수정
PUT http://localhost:8080/api/v1/notice/list/update
content-type: application/json

{
    "noticeId": 5,
    "noticeTitle": "공지사항 http테스트5",
    "noticeContent": "공지사항 내용 http테스트5"
}

### 공지사항 리스트조회
GET http://localhost:8080/api/v1/notice/list

### 공지사항 상세 조회
GET http://localhost:8080/api/v1/notice/list/5/edit

### 공지사항 등록
PUT http://localhost:8080/api/v1/notice/regist
content-type: application/json

{
  "noticeTitle": "200떠라",
  "noticeContent": "공지사항 테스팅23"
}

### 공지사항 삭제
DELETE http://localhost:8080/api/v1/notice/list/16/edit


