### 싱글캘린더조회
GET http://localhost:8080/api/v1/singleCalendar/sean1007@naver.com/list

### 유저 캘린더 추가
PUT http://localhost:8080/api/v1/singleCalendar/add/sean1007@naver.com
Content-Type: application/json

{
  "title": "날짜 테스트123",
  "firstDate": "2023-12-01",
  "lastDate": "2023-12-10",
  "groupId": "12324aa",
  "repeatNum": 2
}

### 싱글캘린더조회
DELETE http://localhost:8080/api/v1/singleCalendar/delete/sean1007@naver.com/1

### 싱글캘린더수정
PUT http://localhost:8080/api/v1/singleCalendar/update
Content-Type: application/json

{
  "singleCalendarId": 6,
  "title": "수정테스팅",
  "startDate": "2023-12-04"
}
