### 싱글캘린더조회
GET http://localhost:8080/api/v1/singleCalendar/sean1007@naver.com/list

### 유저 캘린더 추가
PUT http://localhost:8080/api/v1/singleCalendar/add/sean1007@naver.com
Content-Type: application/json

{
  "title": "날짜 테스트",
  "firstDate": "2023-12-07",
  "lastDate": "2023-12-14",
  "repeatNum": 3
}