### 전체 유저 캘린더 조회
GET http://localhost:8080/api/v1/usercalendar/list

### 유저별 캘린더 조회
GET http://localhost:8080/api/v1/usercalendar/list/zusung1

### 날짜별 캘린더 조회(시작일 기준(날짜가 하루 전으로 출력됨))
GET http://localhost:8080/api/v1/usercalendar/list/StartDate/2023-12-03

### 날짜별 캘린더 조회(종료일 기준(날짜가 하루 전으로 출력됨))
GET http://localhost:8080/api/v1/usercalendar/list/EndDate/2023-12-07

### 유저의 캘린더 수정(일정 등록)
PUT http://localhost:8080/api/v1/usercalendar/update/zusung1
Content-Type: application/json

{
  "startDate": "2023-12-03",
  "endDate": "2023-12-07",
  "title": "러닝하기",
  "calendarContent": "매일 3km 러닝하기",
  "deleteStatus": 0,
  "time": "13:30:00"
}

### 유저 캘린더 추가
PUT http://localhost:8080/api/v1/usercalendar/regist
Content-Type: application/json

{
  "userCalendarId": "1",
  "startDate": "2023-12-08",
  "endDate": "2023-12-14",
  "title": "수영하기",
  "calendarContent": "매일 1km 수영하기",
  "deleteStatus": "0",
  "userId": {
    "userId": "test6",
    "nickname": "test6",
    "diamondCount": 50,
    "joinDate": "2023-11-11",
    "outDate": "2023-11-20",
    "permissionType": "0"
  },
  "time": "14:30:00"
}